#!/bin/bash
# Clear logs generated by system.sh if over 5MB
MAIN_LOG="/home/admin/thesis/maintenance.log"
FILES=("/home/admin/bridge.log" "/home/admin/api.log" "/home/admin/web.log")

for FILE in "${FILES[@]}"; do
    if [ -f "$FILE" ]; then
        if [ $(stat -c%s "$FILE") -gt 5242880 ]; then
            cat /dev/null > "$FILE"
            echo "[$(date)] STORAGE: Rotated log: $FILE" >> "$MAIN_LOG"
        fi
    fi
done
sudo rm -rf /tmp/*
